export const backendBaseUrl =
 process.env.NEXT_PUBLIC_BACKEND_URL ||
 process.env.NEXT_PUBLIC_API_URL ||
 process.env.BACKEND_URL ||
 "https://backend-app-movil-177686674468.europe-west1.run.app";

export const adminApiEndpoints = {
 auth: {
 login: ["/api/login"],
 profile: ["/api/users/me", "/api/profile/current", "/profile", "/api/profile", "/api/profile/me"],
 refresh: ["/api/auth/refresh", "/auth/refresh-token"],
 verify2fa: ["/api/auth/2fa/verify", "/auth/2fa/verify"],
 logout: ["/api/auth/logout", "/auth/logout"],
 },
 dashboard: {
 summary: ["/api/dashboard", "/api/dashboard/summary"],
 attendanceToday: ["/api/dashboard/attendance-today"],
 pendingRequests: ["/api/dashboard/pending-requests"],
 workerStatus: ["/api/dashboard/worker-status"],
 contractsExpiring: ["/api/dashboard/contracts-expiring"],
 documentsPending: ["/api/dashboard/documents-pending"],
 lateWorkers: ["/api/dashboard/late-workers"],
 projectSummary: ["/api/dashboard/project-summary"],
 },
 requests: {
 list: ["/api/requests"],
 my: ["/api/requests/my"],
 types: ["/api/requests/types", "/api/request-types"],
 pending: ["/api/requests/pending", "/api/requests"],
 reports: ["/api/requests/reports"],
 reportPreview: ["/api/requests/reports/preview"],
 reportSummary: ["/api/requests/reports/summary"],
 reportCharts: ["/api/requests/reports/charts"],
 reportColumns: ["/api/requests/reports/columns"],
 reportExportExcel: ["/api/requests/reports/export/excel"],
 reportExportPdf: ["/api/requests/reports/export/pdf"],
 reportExportCsv: ["/api/requests/reports/export/csv"],
 templates: ["/api/requests/templates"],
 },
 reportTemplates: {
 list: ["/api/report-templates"],
 },
 documents: {
 list: ["/api/documents"],
 },
 users: {
 list: ["/api/users"],
 current: ["/api/users/me"],
 preferences: ["/api/users/me/preferences"],
 },
 companySettings: {
 settings: ["/api/company-settings"],
 logo: ["/api/company-settings/logo"],
 signature: ["/api/company-settings/signature"],
 stamp: ["/api/company-settings/stamp"],
 },
 workers: {
 list: ["/api/workers"],
 },
 roles: {
 list: ["/api/roles"],
 },
 profile: {
 current: ["/api/profile/current", "/profile", "/api/profile", "/api/users/me"],
 update: ["/api/profile/current", "/profile", "/api/profile"],
 changePassword: ["/api/profile/password", "/profile/change-password"],
 sessions: ["/api/profile/sessions", "/profile/sessions"],
 sessionsOther: [
    "/api/profile/sessions/others",
    "/api/profile/sessions/other",
    "/profile/sessions/others",
    "/profile/sessions/other",
  ],
 activities: ["/api/profile/activities", "/profile/activities", "/api/users/me/activities"],
 },
 reports: {
 attendance: ["/api/reports/attendance"],
 monthlySummary: ["/api/reports/monthly-summary"],
 requestsPdf: ["/api/reports/requests/pdf"],
 attendancePdfCorporate: ["/api/reports/attendance/pdf", "/api/reports/attendance/export/pdf"],
 workersPdf: ["/api/reports/workers/pdf"],
 payrollPdf: ["/api/reports/payroll/pdf"],
 monthlySummaryPdf: ["/api/reports/monthly-summary/pdf", "/api/reports/monthly-summary/export/pdf"],
 vacationsPdf: ["/api/reports/vacations/pdf"],
 documentsPdf: ["/api/reports/documents/pdf"],
 workCrewsPdf: ["/api/reports/work-crews/pdf"],
 workCrewsExcel: ["/api/reports/work-crews/export/excel"],
 attendanceExcel: ["/api/reports/attendance/export/excel"],
 attendancePdf: ["/api/reports/attendance/export/pdf"],
 monthlySummaryExcel: ["/api/reports/monthly-summary/export/excel"],
 workCrewsColumns: ["/api/reports/work-crews/columns"],
 workCrewsPreview: ["/api/reports/work-crews/preview"],
 },
 payroll: {
 periods: ["/payroll/periods"],
 },
 vacations: {
    myBalance: ["/api/vacations/me/balance", "/api/vacations/balance"],
    workerBalance: ["/api/vacations/workers"],
  },
  attendanceHistory: {
    history: ["/api/attendance/history"],
    summary: ["/api/attendance/summary"],
  },
} as const;

export const webApiEndpoints = {
  auth: {
    login: "/api/auth/login",
    session: "/api/auth/session",
    logout: "/api/auth/logout",
    verifyPassword: "/api/auth/verify-password",
    verify2fa: "/api/auth/2fa/verify",
    changePassword: "/api/auth/change-password",
  },
 dashboard: "/api/dashboard",
 requests: {
 list: "/api/requests",
 my: "/api/requests/my",
 pending: "/api/requests/pending",
 types: "/api/requests/types",
 reports: "/api/requests/reports",
 reportPreview: "/api/requests/reports/preview",
 reportSummary: "/api/requests/reports/summary",
 reportCharts: "/api/requests/reports/charts",
 reportColumns: "/api/requests/reports/columns",
 reportExport: (format: "xlsx" | "pdf" | "csv") => `/api/requests/reports/export/${format}`,
 templates: "/api/requests/templates",
 templateDownload: (templateId: string) => `/api/requests/templates/${templateId}/download`,
 detail: (requestId: string) => `/api/requests/${requestId}`,
 cancel: (requestId: string) => `/api/requests/${requestId}/cancel`,
 review: (requestId: string) => `/api/requests/${requestId}/review`,
 approve: (requestId: string) => `/api/requests/${requestId}/approve`,
 reject: (requestId: string) => `/api/requests/${requestId}/reject`,
 observe: (requestId: string) => `/api/requests/${requestId}/observe`,
 resubmit: (requestId: string) => `/api/requests/${requestId}/resubmit`,
 documents: (requestId: string) => `/api/requests/${requestId}/documents`,
 document: (requestId: string, documentId: string) =>
 `/api/requests/${requestId}/documents/${documentId}`,
 },
  documents: {
    list: "/api/documents",
    types: "/api/documents/types",
    detail: (documentId: string) => `/api/documents/${documentId}`,
    upload: (workerId: string) => `/api/documents/workers/${workerId}`,
    review: (documentId: string) => `/api/documents/${documentId}/review`,
    delete: (documentId: string) => `/api/documents/${documentId}`,
  },
 workers: {
 list: "/api/workers",
 laborAssignment: (id: string) => `/api/workers/${id}/labor-assignment`,
 locationHistory: (id: string) => `/api/workers/${id}/location-history`,
 },
 users: "/api/users",
 companySettings: {
 settings: "/api/company-settings",
 legalInfo: "/api/company-settings/legal-info",
 brand: "/api/company-settings/brand",
 logo: "/api/company-settings/logo",
 signature: "/api/company-settings/signature",
 stamp: "/api/company-settings/stamp",
 },
 roles: "/api/roles",
 profile: {
 me: "/api/users/me",
 current: "/api/profile/current",
 password: "/api/profile/password",
 photo: "/api/profile/photo",
 preferences: "/api/users/me/preferences",
 sessions: "/api/profile/sessions",
 sessionsOther: "/api/profile/sessions/others",
 sessionsOtherFallback: "/api/profile/sessions/other",
 revokeSession: (id: string) => `/api/profile/sessions/${id}`,
 trustSession: (id: string) => `/api/profile/sessions/${id}/trust`,
 activities: "/api/profile/activities",
 },
 reports: "/api/reports",
 corporateReports: {
 requestsPdf: "/api/reports/requests/pdf",
 attendancePdf: "/api/reports/attendance/pdf",
 workersPdf: "/api/reports/workers/pdf",
 payrollPdf: "/api/reports/payroll/pdf",
 monthlySummaryPdf: "/api/reports/monthly-summary/pdf",
 vacationsPdf: "/api/reports/vacations/pdf",
 documentsPdf: "/api/reports/documents/pdf",
 workCrewsPdf: "/api/reports/work-crews/export/pdf",
 workCrewsExcel: "/api/reports/work-crews/export/excel",
 workCrewsColumns: "/api/reports/work-crews/columns",
 workCrewsPreview: "/api/reports/work-crews/preview",
 },
 reportTemplates: {
 list: "/api/report-templates",
 detail: (templateId: string) => `/api/report-templates/${templateId}`,
 },
  payroll: {
    periods: "/api/payroll/periods",
  },
  schedule: {
    policies: "/api/schedule/policies",
    shifts: "/api/schedule/shifts",
    shiftDetail: (id: string) => `/api/schedule/shifts/${id}`,
    assignments: "/api/schedule/assignments",
    assignmentDetail: (id: string) => `/api/schedule/assignments/${id}`,
    workerSchedule: (workerId: string) => `/api/schedule/workers/${workerId}/schedule`,
    workerRestDays: (workerId: string) => `/api/schedule/workers/${workerId}/rest-days`,
    mySchedule: "/api/schedule/profile/my-schedule",
    attendanceSummary: "/api/schedule/attendance-summary",
    holidays: () => "/api/schedule/holidays",
  },
 organization: {
 departments: "/api/departments",
 department: (id: string) => `/api/departments/${id}`,
 departmentStatus: (id: string) => `/api/departments/${id}/status`,
 areas: "/api/areas",
 area: (id: string) => `/api/areas/${id}`,
 areaStatus: (id: string) => `/api/areas/${id}/status`,
 positions: "/api/positions",
 position: (id: string) => `/api/positions/${id}`,
 positionStatus: (id: string) => `/api/positions/${id}/status`,
 workLocations: "/api/work-locations",
 workLocation: (id: string) => `/api/work-locations/${id}`,
 workLocationStatus: (id: string) => `/api/work-locations/${id}/status`,
 },
 geography: {
    departments: "/api/geography/departments",
    provinces: "/api/geography/provinces",
    districts: "/api/geography/districts",
  },
  vacations: {
    myBalance: "/api/vacations/me/balance",
    workerBalance: (workerId: string) => `/api/vacations/workers/${workerId}/balance`,
  },
  attendance: {
    checkIn: "/api/attendance/check-in",
    checkOut: "/api/attendance/check-out",
    history: "/api/attendance/history",
    summary: "/api/attendance/summary",
    analyticsDashboard: "/api/attendance/analytics/dashboard",
    analyticsTable: "/api/attendance/analytics/table",
    analyticsWorker: (workerId: string) => `/api/attendance/analytics/workers/${workerId}`,
    analyticsArea: (areaId: string) => `/api/attendance/analytics/areas/${areaId}`,
    analyticsWorkLocation: (workLocationId: string) => `/api/attendance/analytics/work-locations/${workLocationId}`,
    analyticsCrew: (crewId: string) => `/api/attendance/analytics/crews/${crewId}`,
    analyticsExport: "/api/attendance/analytics/export",
    analyticsExportFilters: "/api/attendance/analytics/export/filters",
    recalculateAnalytics: "/api/attendance/analytics/recalculate",
  },
} as const;
