import { adminApiEndpoints } from "@/lib/api/endpoints";

const appendId = (paths: readonly string[], id: string) => paths.map((path) => `${path}/${id}`);
const appendAction = (paths: readonly string[], id: string, actions: string[]) =>
  actions.flatMap((action) => paths.map((path) => `${path}/${id}/${action}`));

export const backendRoutes = {
  auth: {
    login: adminApiEndpoints.auth.login,
    profile: adminApiEndpoints.auth.profile,
    refresh: adminApiEndpoints.auth.refresh,
    updateProfile: adminApiEndpoints.profile.update,
    changePassword: adminApiEndpoints.profile.changePassword,
  },
  profile: {
    current: adminApiEndpoints.profile.current,
    update: adminApiEndpoints.profile.update,
    changePassword: adminApiEndpoints.profile.changePassword,
  },
  dashboard: {
    summary: adminApiEndpoints.dashboard.summary,
    attendanceToday: adminApiEndpoints.dashboard.attendanceToday,
    pendingRequests: adminApiEndpoints.dashboard.pendingRequests,
    workerStatus: adminApiEndpoints.dashboard.workerStatus,
    contractsExpiring: adminApiEndpoints.dashboard.contractsExpiring,
    documentsPending: adminApiEndpoints.dashboard.documentsPending,
    lateWorkers: adminApiEndpoints.dashboard.lateWorkers,
    projectSummary: adminApiEndpoints.dashboard.projectSummary,
  },
  requests: {
    list: adminApiEndpoints.requests.list,
    my: adminApiEndpoints.requests.my,
    reports: adminApiEndpoints.requests.reports,
    reportPreview: adminApiEndpoints.requests.reportPreview,
    reportSummary: adminApiEndpoints.requests.reportSummary,
    reportCharts: adminApiEndpoints.requests.reportCharts,
    reportColumns: adminApiEndpoints.requests.reportColumns,
    reportExportExcel: adminApiEndpoints.requests.reportExportExcel,
    reportExportPdf: adminApiEndpoints.requests.reportExportPdf,
    reportExportCsv: adminApiEndpoints.requests.reportExportCsv,
    templates: adminApiEndpoints.requests.templates,
    detail: (id: string) => appendId(adminApiEndpoints.requests.list, id),
    cancel: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["cancel"]),
    review: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["review"]),
    approve: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["approve"]),
    reject: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["reject"]),
    observe: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["observe"]),
    resubmit: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["resubmit"]),
    documents: (id: string) => appendAction(adminApiEndpoints.requests.list, id, ["documents"]),
    document: (id: string, documentId: string) =>
      appendAction(adminApiEndpoints.requests.list, id, [`documents/${documentId}`]),
    templateDownload: (id: string) => appendAction(adminApiEndpoints.requests.templates, id, ["download"]),
    types: adminApiEndpoints.requests.types,
    pending: adminApiEndpoints.requests.pending,
  },
  reportTemplates: {
    list: adminApiEndpoints.reportTemplates.list,
    detail: (id: string) => appendId(adminApiEndpoints.reportTemplates.list, id),
  },
  documents: {
    list: adminApiEndpoints.documents.list,
  },
  users: {
    list: adminApiEndpoints.users.list,
    detail: (id: string) => appendId(adminApiEndpoints.users.list, id),
    create: adminApiEndpoints.users.list,
    update: (id: string) => appendId(adminApiEndpoints.users.list, id),
    disable: (id: string) => appendAction(adminApiEndpoints.users.list, id, ["disable"]),
    enable: (id: string) => appendAction(adminApiEndpoints.users.list, id, ["enable"]),
    block: (id: string) => appendAction(adminApiEndpoints.users.list, id, ["block"]),
    suspend: (id: string) => appendAction(adminApiEndpoints.users.list, id, ["suspend"]),
  },
  companySettings: {
    settings: adminApiEndpoints.companySettings.settings,
    logo: adminApiEndpoints.companySettings.logo,
    signature: adminApiEndpoints.companySettings.signature,
    stamp: adminApiEndpoints.companySettings.stamp,
  },
  workers: {
    list: adminApiEndpoints.workers.list,
    detail: (id: string) => appendId(adminApiEndpoints.workers.list, id),
    create: adminApiEndpoints.workers.list,
    update: (id: string) => appendId(adminApiEndpoints.workers.list, id),
    disable: (id: string) => appendAction(adminApiEndpoints.workers.list, id, ["disable"]),
    enable: (id: string) => appendAction(adminApiEndpoints.workers.list, id, ["enable"]),
  },
  reports: {
    attendance: adminApiEndpoints.reports.attendance,
    monthlySummary: adminApiEndpoints.reports.monthlySummary,
    requestsPdf: adminApiEndpoints.reports.requestsPdf,
    attendancePdfCorporate: adminApiEndpoints.reports.attendancePdfCorporate,
    workersPdf: adminApiEndpoints.reports.workersPdf,
    payrollPdf: adminApiEndpoints.reports.payrollPdf,
    monthlySummaryPdf: adminApiEndpoints.reports.monthlySummaryPdf,
    vacationsPdf: adminApiEndpoints.reports.vacationsPdf,
    documentsPdf: adminApiEndpoints.reports.documentsPdf,
    workCrewsPdf: adminApiEndpoints.reports.workCrewsPdf,
    workCrewsExcel: adminApiEndpoints.reports.workCrewsExcel,
    workCrewsColumns: adminApiEndpoints.reports.workCrewsColumns,
    workCrewsPreview: adminApiEndpoints.reports.workCrewsPreview,
    list: [
      ...adminApiEndpoints.reports.attendance,
      ...adminApiEndpoints.reports.monthlySummary,
    ],
    attendanceExcel: adminApiEndpoints.reports.attendanceExcel,
    attendancePdf: adminApiEndpoints.reports.attendancePdf,
    monthlySummaryExcel: adminApiEndpoints.reports.monthlySummaryExcel,
  },
  payroll: {
    periods: adminApiEndpoints.payroll.periods,
  },
  roles: {
    list: adminApiEndpoints.roles.list,
  },
};
